//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeManager.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfficeManager.Domain.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do cliente do caso está vazio ou nulo.
        /// </summary>
        internal static string CaseClientIdIsEmpty {
            get {
                return ResourceManager.GetString("CaseClientIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do caso está vazia ou nula.
        /// </summary>
        internal static string CaseDescriptionIsEmpty {
            get {
                return ResourceManager.GetString("CaseDescriptionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do caso está vazio ou nulo.
        /// </summary>
        internal static string CaseIdIsEmpty {
            get {
                return ResourceManager.GetString("CaseIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do caso está vazio ou nulo.
        /// </summary>
        internal static string CaseNameIsEmpty {
            get {
                return ResourceManager.GetString("CaseNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status do caso está vazio ou nulo.
        /// </summary>
        internal static string CaseStatusIsEmpty {
            get {
                return ResourceManager.GetString("CaseStatusIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O endereço do cliente está vazio ou nulo.
        /// </summary>
        internal static string ClientAddressIsEmpty {
            get {
                return ResourceManager.GetString("ClientAddressIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF do cliente está vazio ou nulo.
        /// </summary>
        internal static string ClientCpfIsEmpty {
            get {
                return ResourceManager.GetString("ClientCpfIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email do cliente está vazio ou nulo.
        /// </summary>
        internal static string ClientEmailIsEmpty {
            get {
                return ResourceManager.GetString("ClientEmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do cliente está vazio ou nulo.
        /// </summary>
        internal static string ClientIdIsEmpty {
            get {
                return ResourceManager.GetString("ClientIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do cliente do atendimento está vazio ou nulo.
        /// </summary>
        internal static string ClientMeetingClientIdIsEmpty {
            get {
                return ResourceManager.GetString("ClientMeetingClientIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do atendimento está vazia ou nula.
        /// </summary>
        internal static string ClientMeetingDescriptionIsEmpty {
            get {
                return ResourceManager.GetString("ClientMeetingDescriptionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do atendimento está vazio ou nulo.
        /// </summary>
        internal static string ClientMeetingIdIsEmpty {
            get {
                return ResourceManager.GetString("ClientMeetingIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data do atendimento está vazia ou nula.
        /// </summary>
        internal static string ClientMeetingMeetingDateIsEmpty {
            get {
                return ResourceManager.GetString("ClientMeetingMeetingDateIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do cliente está vazio ou nulo.
        /// </summary>
        internal static string ClientNameIsEmpty {
            get {
                return ResourceManager.GetString("ClientNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do escritório do cliente está vazio ou nulo.
        /// </summary>
        internal static string ClientOfficeIdIsEmpty {
            get {
                return ResourceManager.GetString("ClientOfficeIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone do cliente está vazio ou nulo.
        /// </summary>
        internal static string ClientPhoneIsEmpty {
            get {
                return ResourceManager.GetString("ClientPhoneIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do caso do documento está vazio ou nulo.
        /// </summary>
        internal static string DocumentCaseIdIsEmpty {
            get {
                return ResourceManager.GetString("DocumentCaseIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do documento está vazio ou nulo.
        /// </summary>
        internal static string DocumentIdIsEmpty {
            get {
                return ResourceManager.GetString("DocumentIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do documento está vazio ou nulo.
        /// </summary>
        internal static string DocumentNameIsEmpty {
            get {
                return ResourceManager.GetString("DocumentNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A URL do documento está vazia ou nula.
        /// </summary>
        internal static string DocumentUrlIsEmpty {
            get {
                return ResourceManager.GetString("DocumentUrlIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do honorário está vazio ou nulo.
        /// </summary>
        internal static string FeeAmountIsEmpty {
            get {
                return ResourceManager.GetString("FeeAmountIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do caso do honorário está vazio ou nulo.
        /// </summary>
        internal static string FeeCaseIdIsEmpty {
            get {
                return ResourceManager.GetString("FeeCaseIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do honorário está vazio ou nulo.
        /// </summary>
        internal static string FeeIdIsEmpty {
            get {
                return ResourceManager.GetString("FeeIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status do pagamento do honorário está vazio ou nulo.
        /// </summary>
        internal static string FeePaymentStatusIsEmpty {
            get {
                return ResourceManager.GetString("FeePaymentStatusIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do usuário do honorário está vazio ou nulo.
        /// </summary>
        internal static string FeeUserIdIsEmpty {
            get {
                return ResourceManager.GetString("FeeUserIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CNPJ do escritório está vazio ou nulo.
        /// </summary>
        internal static string OfficeCnpjIsEmpty {
            get {
                return ResourceManager.GetString("OfficeCnpjIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do escritório está vazio ou nulo.
        /// </summary>
        internal static string OfficeIdIsEmpty {
            get {
                return ResourceManager.GetString("OfficeIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do escritório está vazio ou nulo.
        /// </summary>
        internal static string OfficeNameIsEmpty {
            get {
                return ResourceManager.GetString("OfficeNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de nascimento do usuário está vazia ou nula.
        /// </summary>
        internal static string UserBirthDateIsEmpty {
            get {
                return ResourceManager.GetString("UserBirthDateIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do usuário está vazio ou nulo.
        /// </summary>
        internal static string UserEmailIsEmpty {
            get {
                return ResourceManager.GetString("UserEmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do usuário está vazio ou nulo.
        /// </summary>
        internal static string UserIdIsEmpty {
            get {
                return ResourceManager.GetString("UserIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário está vazio ou nulo.
        /// </summary>
        internal static string UserNameIsEmpty {
            get {
                return ResourceManager.GetString("UserNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do escritório do usuário está vazio ou nulo.
        /// </summary>
        internal static string UserOfficeIdIsEmpty {
            get {
                return ResourceManager.GetString("UserOfficeIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha do usuário está vazia ou nula.
        /// </summary>
        internal static string UserPasswordIsEmpty {
            get {
                return ResourceManager.GetString("UserPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O perfil do usuário está vazio ou nulo.
        /// </summary>
        internal static string UserProfileIsEmpty {
            get {
                return ResourceManager.GetString("UserProfileIsEmpty", resourceCulture);
            }
        }
    }
}
